- README.md
There are three examples which still have utilized `C.*` instead of `S.*`
> docs: fix types that still refer to Codec

- src/Schema.ts
- test/Schema.ts
I'd like to be able to use `extend` on unions of structs.
```typescript
pipe(
S.struct({ b: S.boolean }),
S.extend(S.union(
S.struct({ a: S.literal("a") }),
S.struct({ a: S.literal("b") })
))
)
```
I've added an implementation that enables combination of 
- typeLiteral with union of typeLiterals,
- union of typeLiterals with typeLiteral
- union of typeLiterals with another union of typeLiterals
> feat: allow extend on union types

- README.md
While going through the examples, I found that `format` doesn't exist anymore and seems to have been renamed into `formatErrors`.
**Before submitting a pull request,** please make sure the following is done:
- Fork [the repository](https://github.com/gcanti/fp-ts) and create your branch from `master` (\*).
- Run `npm install` in the repository root.
- If you've fixed a bug or added code that should be tested, add tests!
- Ensure the test suite passes (`npm test`).
**Note**. If you've fixed a bug please link the related issue or, if missing, open an issue before sending a PR.
**Note**. If you find a typo in the **documentation**, make sure to modify the corresponding source (docs are generated).
(\*)
- if you want to send a PR related to `fp-ts@1.x` please create your branch from `1.x`
- …
> Use `formatErrors` instead of `format`

- README.md
The following commit removed `transform` from the ParseError module:
https://github.com/fp-ts/schema/commit/27e54bb031df7fda429f8a6d3e56ac87484a96a7
> Update README to reflect removal of `transform` from ParseError

- src/Schema.ts
- test/Arbitrary.ts
- test/Schema.ts
Hey,
after [adding the support for union types](https://github.com/fp-ts/schema/pull/34), the `extend` allows the following construction
```typescript
pipe(
S.struct({ a: S.literal("a") }),
S.extend(
S.union(
S.struct({ a: S.literal("b"), b: S.string }),
S.struct({ a: S.literal("a"), b: S.number })
)
)
)
```
which has an expected type
```typescript
S.Schema<{
readonly a: "a";
readonly b: number;
}>
```
but in the term-level code the AST is a union where each element has a duplicated `a` literal. As a consequence, fast-check generates a non-sensical object `{"a":"b","b":""}`.
One solution is simply not supporting overlapping properties for the `extend` combinator but I find it super useful to be able to extend with an union where each element can discriminate with its field.
Therefore, in …
> fix: extend union with mutually exclusive properties

- src/Parser.ts
- test/Encoder.ts
Hey, during implementation of a schema for an integer parsed from a string (running a refinement on top of a transformation) I noticed the encoder returns a failure unexpectedly. Here's my example schema.
```typescript
pipe(P.parseNumber(S.string), S.int())
```
The problem seems to be in the `Refinement` implementation. It runs the refinement check after running parsing on the `ast.from`. I think for the `encoder` case it should be the other way around and it looks like it fixed the issue.
> fix: encoder refinement

- .changeset/mighty-feet-warn.md
- src/data/Brand.ts
- test/data/Brand.ts
Added data/Brand. Accepts either a `Brand` type or a `RefinedConstructors` to establish the brand. In the first case the brand is simply attached at the type level and in the latter case the value is tested against the `RefinedConstructors.refine` function before the brand is attached.
> feat: added data/Brand

- README.md
It looks like `S.json` was removed in this PR: https://github.com/fp-ts/schema/pull/68
...but it is still referenced as a primitive in the README. Removing as it is no longer exported.
> Remove json primitive in README

- .changeset/empty-ducks-kick.md
- README.md
- src/Schema.ts
- src/data/Bigint.ts
- src/data/Number.ts
- test/data/Bigint.ts
- test/data/Number.ts
Duplicated the functionality of data/Number to data/Bigint and added between and betweenExclusive filters for both modules. Using data/Bigint must be namespaced due to name collisions with number.
> feat: added data/Bigint and N.between

- src/AST.ts
- test/AST.ts
It correctly unify the union of a boolean literal with the `boolean` primitive, and the union of a bigint with the `bigint` one.
> fix: enhance union unification for boolean and bigint literals

- src/Schema.ts
The description for S.date is incorrect.
> fix: removed incorrect description for S.date

- README.md
AST doesn't expose Union or Literal for me. It exposes createUnion or createLiteral. Therefore, this change proposes to change the example accordingly.
> changes documentation example for transformations

- .changeset/tricky-rockets-drop.md
- README.md
- dtslint/ts4.7/Schema.ts
- src/AST.ts
- src/Schema.ts
- test/AST.ts
- test/Schema.ts
Adds S.required
```js
const schema = S.required(S.struct({ a: S.optional(S.number) }))
expectParseSuccess(schema, { a: 1 }, { a: 1 })
expectParseFailure(schema, {}, "/a is missing")
```
https://github.com/colinhacks/zod#required
> feat: added S.required combinator

- .changeset/flat-squids-exist.md
- README.md
- docs/modules/Schema.ts.md
- src/Schema.ts
- test/data/Date.ts
Currently numberFromString returns a function returning a Schema while dateFromString just returns a Schema. Limitation on the latter being that you can't enforce limitations such as string size of the input string.
> fix: align dateFromString with numberFromString

- .changeset/cold-masks-sit.md
- README.md
- docs/modules/Schema.ts.md
- package.json
- pnpm-lock.yaml
- src/Schema.ts
- test/Schema.ts
- test/data/filter/ULID.ts
The PR implements a schema for [ULID](https://github.com/ulid/spec)s, similarly to UUID. This requires an upgrade of `fast-check` where I introduced the ULID arbitrary in https://github.com/dubzzz/fast-check/pull/4020.
> Add ulid schema

- src/Schema.ts
- test/data/Object.ts
Fixed: Annotations such as `message` are ignored when using `S.instanceOf`.
> Fix instanceOf annotations

- .changeset/shiny-bags-float.md
- .changeset/slimy-walls-obey.md
- docs/modules/Schema.ts.md
- package.json
- pnpm-lock.yaml
- src/Schema.ts
- test/Schema.ts
In effect-http, I need a runtime check for whether an object is a `Schema`. I could do it in the lib structurally by checking the `ast` field but that is verbose and probably prone to errors when the AST changes.
> feat: add `isSchema` guard

- .changeset/beige-stingrays-move.md
- README.md
- src/Schema.ts
- test/data/Bigint.ts
Implements #351.
Sometimes resource identifiers are very large integers represented as strings, e.g. through query params, and sometimes also via the response body, but stored as integers in the database. This schema will help parse such inputs.
> Add schema for BigintFromString

- .changeset/gold-ladybugs-bow.md
- README.md
- src/Schema.ts
- test/data/String.ts
Partially addresses #352 as a response to the received feedback in #353.
The idea is that once we can split strings into arrays of strings, we could implement another combinator that allows transforming arrays of type I into arrays of type A. With those two combinators: `split`, and `arrayOf`, we could implement the same as the proposed `arrayFromDelimitedString` by chaining those combinators like so:
```ts
S.string.pipe(S.split(","), S.arrayOf(S.NumberFromString))
```
> Add combinator that splits a string into an array of strings

- .changeset/nice-ants-push.md
- README.md
- src/Schema.ts
- test/compose.ts
Fully addresses https://github.com/Effect-TS/schema/issues/352 in combination with https://github.com/Effect-TS/schema/pull/359 as opposed to the approach outlined in https://github.com/Effect-TS/schema/pull/353.
Based on the suggestion from https://github.com/Effect-TS/schema/pull/359#issuecomment-1651019819.
The `compose` combinator allows one to directly transform `Schema<A, B>` to `Schema<B, C>` creating a `Schema<A, C>`.
> Add `compose`

- README.md
> fix `mapBoth` signature in `transformResult` example

- .changeset/olive-colts-thank.md
- docs/modules/Schema.ts.md
- src/Schema.ts
- test/Uint8Array/Uint8Array.ts
- test/Uint8Array/Uint8ArrayFromSelf.ts
Normally Uint8Array is serialized as an obect. I chose to serialize it as an array here which is a bit more compact and had some other benefits.
I'd like to add `hex` and `base64` schema support on top.
> Add support for Uint8Array

- .changeset/lazy-pigs-cross.md
- docs/modules/Schema.ts.md
- src/Schema.ts
- test/Arbitrary/Class.ts
@tim-smart It's super easy to forget passing in the self-referencing `S.Class<>` type parameter (./cc @datner)
I'm not sure if there's a better way to solve this dx issue but this at least blows up if you forget to pass it ;-)
> require explicit type parameter for dx

- docs/modules/Schema.ts.md
- src/Schema.ts
Sorry @tim-smart, I think this is nicer. Keep the `unknown` in place instead of defaulting to `never` in case of failed inferrence (so always unless passed explicitly).
> don't default to `never`

- .changeset/light-taxis-impress.md
- docs/modules/Parser.ts.md
- docs/modules/Schema.ts.md
- src/Parser.ts
- src/Schema.ts
- test/Parser.test.ts
- test/Schema/exports.test.ts
- test/Schema/parseJson.test.ts
- test/dev.test.ts
- decodeResult (use decode instead)
- encodeResult (use encode instead)
- parseResult (use parse instead)
- validateResult (use validate instead)
> Schema: remove *Result APIs

- .changeset/plenty-sheep-clean.md
- src/Parser.ts
- test/Parser.test.ts
`_getLiterals` should consider the case it is an encoding operation.
```typescript
P.encodeSync(
S.union(
S.transform(
S.struct({ _tag: S.literal("a") }),
S.struct({ _tag: S.literal("b") }),
() => ({ _tag: "b" as const }),
() => ({ _tag: "a" as const })
),
S.struct({ _tag: S.literal("c") })
)
)({ _tag: "b" })
// BEFORE:
// Error: error(s) found
// └─ ["_tag"]
//    └─ Expected "a" or "c", actual "b"
// NOW:
// { _tag: "a" }
P.encodeSync(
S.union(
S.struct({
_tag: S.transform(
S.literal("a"),
S.literal("b"),
() => "b" as const,
() => "a" as const
)
}),
S.struct({ _tag: S.literal("c") })
)
)({ _tag: "b" })
// BEFORE:
// Error: error(s) found
// └─ ["_tag"]
//    └─ Expected "a" or "c", actual "b"
// NOW:
// { _tag: "a" }
```
> fix encode discriminated union with transformation

- .changeset/tough-fireants-shop.md
- src/Schema.ts
- test/Schema/brand.test.ts
Replaced TreeFormatter with ArrayFormatter for BrandErrors when using Schema.brand
> feat: updated Schema.brand BrandError

- .github/workflows/main.yml
I accidentally removed this.
The `version` script is optional (e.g. in case one wants to run custom scripts before or after versioning). But the `publish` script is required if one wants to publish. Since we don't run any custom logic there we can just do `pnpm changeset publish` directly.
> fix changeset publishing

- .changeset/cyan-vans-brake.md
- README.md
- docs/modules/Schema.ts.md
- dtslint/Schema.ts
- src/AST.ts
- src/Schema.ts
- src/internal/common.ts
- test/Schema/PropertySignatureTransformations.test.ts
- test/Schema/rename.test.ts
To rename one or more properties, you can utilize the `rename` API:
```ts
import * as Schema from "@effect/schema/Schema";
// Original Schema
const originalSchema = Schema.struct({ a: Schema.string, b: Schema.number });
// Renaming the "a" property to "c"
const renamedSchema = Schema.rename(originalSchema, { a: "c" });
Schema.parseSync(renamedSchema)({ a: "a", b: 1 }); // Output: { c: "a", b: 1 }
```
In the example above, we have an original schema with properties "a" and "b." Using the `rename` API, we create a new schema where we rename the "a" property to "c." The resulting schema, when used with `Schema.parseSync`, transforms the input object by renaming the specified property.
> add rename API, closes #549

- .changeset/giant-clocks-compete.md
- docs/modules/ParseResult.ts.md
- src/ArrayFormatter.ts
- src/ParseResult.ts
- src/Parser.ts
- src/TreeFormatter.ts
- test/ArrayFormatter.test.ts
- test/Schema/allErrors.test.ts
- test/Schema/is.test.ts
- test/Schema/onExcess.test.ts
- test/Schema/record.test.ts
- test/Schema/struct.test.ts
- test/TreeFormatter.test.ts
- test/util.ts
Current behaviour: 
```
for each key in input
for each index signature
validate key
validate value
```
Correct behaviour: 
```
for each key in input
for each index signature
if key is valid then validate value
```
RE: https://github.com/gcanti/io-ts/issues/704
> Bug Fix: align index signature behaviour to TypeScript

- .changeset/shy-eggs-march.md
- docs/modules/JSONSchema.ts.md
- src/AST.ts
- src/JSONSchema.ts
- src/Schema.ts
- test/JSONSchema.test.ts
- rename `dependencies` to `$defs`
- remove `"type"` from const schemas
- use `"oneOf"` for enums and add `"title"`s
- add support for `record(pattern, number)`
- add `"$id"` and `"$comment"` properties
- literals should be converted to `enum` instead of `anyOf`, closes #579
> improve JSON Schema output

- .changeset/calm-rules-refuse.md
- docs/modules/JSONSchema.ts.md
- src/JSONSchema.ts
I started seeing `Cannot find name 'JsonSchema7Top'.`
> fix: expose `JsonSchema7Top` and `JsonSchema7` dts

- .changeset/plenty-spies-invite.md
- docs/modules/Schema.ts.md
- src/Schema.ts
- test/Schema/Class.test.ts
Adds a default toString method to schema classes that uses the compiled Pretty instance.
> feat: added toString for Schema classes

- README.md
While not a major issue I believe this helps newcomers to reduce overhead when copy & pasting from examples.
> README: align imports in the readme

- README.md
When going through the documentation I was looking for the equivalent of this simple Zod use-case. The way the README was structured regarding extracting inferred types quite confused me.
```ts
import { z } from "zod";
const User = z.object({
username: z.string(),
});
User.parse({ username: "Ludwig" });
// extract the inferred type
type User = z.infer<typeof User>;
// { username: string }
```
This is an attempt to make it more approachable for newcomers by clearly separating the 99% use-cases from the advanced usage.
> README: clarify extracting inferred types
