- src/data/filter.ts
- test/data/filter/MultipleOf.ts
Add multipleOf for numeric multiplicity. Closes issue #38
> feat: added filter/multipleOf

- src/data/Date.ts
- src/data/parser.ts
- test/data/Date.ts
- test/data/parser/parseDate.ts
Do we want to make parseDate more strict?
> feat: add date

- .changeset/good-ducks-camp.md
- docs/modules/ParseResult.ts.md
- docs/modules/Parser.ts.md
- docs/modules/Pretty.ts.md
- docs/modules/Schema.ts.md
- docs/modules/data/Json.ts.md
- docs/modules/data/Option.ts.md
- docs/modules/data/ReadonlyMap.ts.md
- docs/modules/data/ReadonlySet.ts.md
- docs/modules/data/UUID.ts.md
- docs/modules/data/filter.ts.md
- docs/modules/data/parser.ts.md
- docs/modules/formatter/Tree.ts.md
- docs/modules/index.ts.md
- test/Arbitrary.ts
- test/Pretty.ts
Bug fix: 
- Parser + Arbitrary: favour property signatures over index signatures  
- Pretty: fix duplicated keys in presence of property signatures + index signatures
> version 0.1.2

- .changeset/mighty-feet-warn.md
- src/data/Brand.ts
- test/data/Brand.ts
> feat: added data/Brand (#40)

- .github/workflows/main.yml
- .github/workflows/pr.yml
Added a test for circularity to github actions
> chore(.github): added circular dep check

- .changeset/sweet-peas-remember.md
- README.md
- src/Schema.ts
- src/data/Number.ts
- test/data/Number.ts
Extended data/Number to include positive, negative, nonPositive, nonNegative. Similar to [zod](https://github.com/colinhacks/zod#numbers).
> extended data/Number

- .changeset/unlucky-ants-learn.md
- README.md
- src/Schema.ts
- src/data/ReadonlyArray.ts
- test/data/ReadonlyArray.ts
> added data/ReadonlyArray

- .changeset/metal-pets-remember.md
- src/data/Bigint.ts
- src/formatter/Tree.ts
- test/data/Bigint.ts
> format bigints

- .changeset/modern-cooks-dress.md
- src/data/Bigint.ts
- src/data/Number.ts
Fixes #108. This is my first contribution, so please let me know if I missed any steps or if you have any requested changes. 
Thank you for your continued work on the project. If were not for fp-ts, I would have found a new career years ago.
> fix errata in jsonSchema annotation for Number.between

- .changeset/wild-bananas-act.md
- README.md
- src/Schema.ts
- src/data/Bigint.ts
- src/data/Number.ts
- test/Schema.ts
- test/data/Bigint.ts
- test/data/Number.ts
Added clamp transform to Number, Bigint. Feature parity with @effect-ts/data/Number
> feat: added clamp to Number, Bigint

- .changeset/breezy-eyes-wink.md
- docs/modules/ParseResult.ts.md
- docs/modules/Parser.ts.md
- docs/modules/Schema.ts.md
- src/Arbitrary.ts
- src/ParseResult.ts
- src/Parser.ts
- src/Schema.ts
- src/TreeFormatter.ts
- test/Schema.ts
- test/util.ts
We'll need to add test cases to cover the newly introduced branching
> Only run effects when allowed

- src/AST.ts
- src/Schema.ts
Small docs change. Added/updated categories for docs
> chore(docs): updated categories

- .changeset/rare-games-sing.md
- src/AST.ts
Going through the code, I noticed some guards were missing, so I added them :)
> feat: Added missing assertion functions for some AST nodes

- .changeset/shiny-carrots-cheat.md
- README.md
- src/Schema.ts
- test/data/Boolean.ts
Added S.not to negate boolean values
> feat: added S.not

- .changeset/fluffy-cobras-search.md
- README.md
- src/Schema.ts
- test/lowercase.ts
Added S.lowercase, S.lowercased, S.Lowercase
> feat: added lowercase combinators

- src/Schema.ts
Sorry... My OCD was triggered by this :-/
> ocd code comment fixes

- .changeset/big-gorillas-itch.md
- package.json
- pnpm-lock.yaml
We really need some tooling for this :-P
> fix peer deps version range

- .changeset/lemon-rice-smile.md
- docs/modules/Schema.ts.md
- src/Schema.ts
- test/string/uppercase.test.ts
This is basically a copy + paste and find + replace based on the `lowercase` combinators.
> Add uppercase combinators

- .changeset/serious-eels-allow.md
- docs/modules/ParseResult.ts.md
- src/ParseResult.ts
- src/Schema.ts
Added ParseResult.try which wraps Either.try
> feat: added ParseResult.try

- README.md
Re: https://discord.com/channels/795981131316985866/847382157861060618/1178298289905475605
> README: more pick and omit examples

- README.md
RE: https://discord.com/channels/795981131316985866/1163661991198601308/1163662988696354917
> README: Include a note about the "opaque type" technique.

- .changeset/unlucky-donuts-admire.md
- README.md
- docs/modules/Schema.ts.md
- dtslint/Schema.ts
- src/Schema.ts
- test/Secret/Secret.test.ts
- test/Secret/SecretFromSelf.test.ts
> feat: added Secret

- .changeset/old-countries-act.md
- docs/modules/Arbitrary.ts.md
- src/Arbitrary.ts
while this is mainly useful to me, for tsplus, would there be any objection using the interface here?
> improve: Actually use Arbitrary interface in to/from/unsafe signature

- README.md
We welcome contributions via pull requests! Here are some guidelines to help you get started:
1. Fork the repository and clone it to your local machine.
2. Create a new branch for your changes: `git checkout -b my-new-feature`
3. Install dependencies: `pnpm install` (`pnpm@8.x`)
4. Make your changes and add tests if applicable.
5. Run the tests: `pnpm test`
6. Create a changeset for your changes: before committing your changes, create a changeset to document the modifications. This helps in tracking and communicating the changes effectively. To create a changeset, run the following command: `pnpm changeset`.
7. Commit your changes: after creating the changeset, commit your changes with a descriptive commit message: `git commit -am 'Add some feature'`.
8. Push your changes to your fork: …
> docs(README): remove useless `pipe` imports from examples
